### PR TITLE
Feature: Youtube, Facebook, Twitter, Instagram and other links paste embed

### PR DESCRIPTION
**Pull request by mohsinayoob**

### CODE REVIEW

**Comment by literakl** [comment]
use a pattern in Vuex to accesss external resources

**Comment by mohsinayoob** [comment]
tried to use Vuex along with already integrated axios. axios provide API calls in async fashion but toDOM of tiptap does not support async. If we try to use async call it badly fails. now looking to integrate synchronous approach in Vuex.

**Comment by mohsinayoob** [comment]
Vuex is also async which will not work wit tiptap onDom callback function. I had added an action in Vuex but at the end I had to add a sync API calling util for this feature. I have commented Vuex part of this feature.

**Review by literakl — APPROVED** [review]
I will need to look to that extra dependency sync-fetch at my IDE

**Pull request merged**
